export const GET_FAVORITE_MOVIES_REQUEST = "GET_FAVORITE_MOVIES_REQUEST";
export const GET_FAVORITE_MOVIES_SUCCESS = "GET_FAVORITE_MOVIES_SUCCESS";
export const GET_FAVORITE_MOVIES_FAIL = "GET_FAVORITE_MOVIES_FAIL";

export const REMOVE_FAVORITE_MOVIES = "REMOVE_FAVORITE_MOVIES";
