export const SEARCH_BY_MOVIE_TITLE_REQUEST = "SEARCH_BY_MOVIE_TITLE_REQUEST";
export const SEARCH_BY_MOVIE_TITLE_SUCCESS = "SEARCH_BY_MOVIE_TITLE_SUCCESS";
export const SEARCH_BY_MOVIE_TITLE_FAIL = "SEARCH_BY_MOVIE_TITLE_FAIL";
