export const SEARCH_BY_MOVIE_TITLE_REQUEST = "SEARCH_BY_MOVIE_TITLE_REQUEST";
export const SEARCH_BY_MOVIE_TITLE_SUCCESS = "SEARCH_BY_MOVIE_TITLE_SUCCESS";
export const SEARCH_BY_MOVIE_TITLE_FAIL = "SEARCH_BY_MOVIE_TITLE_FAIL";

export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";
